/**
 * Balance report generator. Runs a battery of sweeps against the real engine and
 * writes balance/REPORT.md plus a console summary. Exits non-zero if any balance
 * invariant is violated, so it can gate CI.
 *
 *   npx tsx balance/report.ts        (or: npm run balance)
 */
import { writeFileSync } from 'fs'
import { RNG } from '../src/game/core/rng'
import { getNode } from '../src/game/data/archetypeTree'
import { RARITY, RARITY_ORDER, generateItem } from '../src/game/data/items'
import { computeCombat } from '../src/game/engine/combat'
import type { Enchantment, Item, ItemRarity, Sentinel } from '../src/game/types'
import { buildSpec, mean, median, runBattle, soloOffense, std, SUPPORT_SPECS, TIER2_NODES } from './harness'

const f1 = (n: number) => n.toFixed(1)
const f2 = (n: number) => n.toFixed(2)
const pct = (n: number) => `${(n * 100).toFixed(0)}%`
const md: string[] = []
const failures: string[] = []
const line = (s = '') => md.push(s)

line('# Fieldwatch — Balance Report')
line('')
line('_Generated by `balance/report.ts` against the live combat engine (seeded, reproducible)._')
line('')

// -------------------------------------------------------------- Sweep 1
// Solo-offense throughput for every specialization (epic gear).
line('## 1. Specialization throughput (all 27, Epic gear)')
line('')
line('Each build fights a fixed tanky wave solo; **DPS = damage dealt ÷ time**. Support')
line('builds (heals/shields/buffs) are expected to read low here and are measured in §2.')
line('')

interface SpecRow {
  id: string
  name: string
  archetype: string
  support: boolean
  dps: number
  analyticDps: number
  cleared: boolean
  timeSec: number
}
const specRows: SpecRow[] = []
for (const node of TIER2_NODES) {
  const m = soloOffense(node.id, { gearRarity: 'epic', seed: 7 })
  const built = buildSpec(node.id, { gearRarity: 'epic', seed: 7 })
  specRows.push({
    id: node.id,
    name: node.name,
    archetype: node.archetype,
    support: SUPPORT_SPECS.has(node.id),
    dps: m.timeSec > 0 ? m.totalDamage / m.timeSec : 0,
    analyticDps: computeCombat(built).dps,
    cleared: m.cleared,
    timeSec: m.timeSec,
  })
}
const offense = specRows.filter((r) => !r.support)
const offDps = offense.map((r) => r.dps)
const offMean = mean(offDps)
const offStd = std(offDps)
const offMed = median(offDps)

specRows.sort((a, b) => b.dps - a.dps)
line('| Build | Archetype | Role | Empirical DPS | Analytic DPS | Cleared | vs median |')
line('|---|---|---|--:|--:|:-:|--:|')
for (const r of specRows) {
  const ratio = offMed ? r.dps / offMed : 0
  const flag = !r.support && (r.dps > offMean + 2 * offStd || r.dps < offMean - 2 * offStd) ? ' ⚠️' : ''
  line(
    `| ${r.name}${flag} | ${r.archetype} | ${r.support ? 'support' : 'offense'} | ${f1(r.dps)} | ${f1(r.analyticDps)} | ${r.cleared ? '✓' : '—'} | ${f2(ratio)}× |`,
  )
}
line('')
line(`Offense builds — mean **${f1(offMean)}**, median **${f1(offMed)}**, σ **${f1(offStd)}**, spread **${f2(Math.max(...offDps) / Math.min(...offDps))}×** (max/min).`)
line('')

// Invariants: no broken (0-dmg) build; no extreme offensive outlier.
for (const r of specRows) {
  if (r.dps <= 0) failures.push(`Build "${r.name}" dealt no damage (broken).`)
}
const worstRatio = Math.max(...offDps) / offMed
if (worstRatio > 3) failures.push(`Offense spread too wide: top build is ${f2(worstRatio)}× the median (>3×).`)

// -------------------------------------------------------------- Sweep 2
// Support value: does adding a support raise a damage team's clear performance?
line('## 2. Support value (team uplift)')
line('')
line('A control team of two damage dealers vs. the same two plus each support, on the')
line('same wave. **Uplift** = reduction in clear time (or added kills if not cleared).')
line('')
const dd1 = buildSpec('sharpshooter', { gearRarity: 'epic', seed: 3 })
const dd2 = buildSpec('pyromancer', { gearRarity: 'epic', seed: 4 })
const control = runBattle({
  team: [
    { sentinel: dd1, slotId: 's3' },
    { sentinel: dd2, slotId: 's1' },
  ],
  depth: 8,
  enemyHpMult: 1.6,
  baseHp: 40,
  maxSeconds: 90,
  seed: 11,
})
line('| Support | Control clear | With support | Δ time | Δ base HP |')
line('|---|--:|--:|--:|--:|')
for (const sid of SUPPORT_SPECS) {
  const sup = buildSpec(sid, { gearRarity: 'epic', seed: 5 })
  const withSup = runBattle({
    team: [
      { sentinel: dd1, slotId: 's3' },
      { sentinel: dd2, slotId: 's1' },
      { sentinel: sup, slotId: 's5' },
    ],
    depth: 8,
    enemyHpMult: 1.6,
    baseHp: 40,
    maxSeconds: 90,
    seed: 11,
  })
  const dTime = control.timeSec - withSup.timeSec
  const dHp = withSup.baseHpLeft - control.baseHpLeft
  line(`| ${getNode(sid).name} | ${f1(control.timeSec)}s | ${f1(withSup.timeSec)}s | ${dTime >= 0 ? '−' : '+'}${f1(Math.abs(dTime))}s | ${dHp >= 0 ? '+' : ''}${f1(dHp)} |`)
}
line('')

// -------------------------------------------------------------- Sweep 3
// Rarity budget ladder (monotonic check).
line('## 3. Item rarity ladder')
line('')
line('Average base-stat budget and enchant count over 400 rolled weapons per tier.')
line('')
line('| Rarity | Avg base-stat total | Avg enchants | Config slots |')
line('|---|--:|--:|--:|')
const rarBudget: Record<string, number> = {}
for (const rar of RARITY_ORDER) {
  const rng = new RNG(99)
  let statSum = 0
  let enchSum = 0
  const N = 400
  for (let i = 0; i < N; i++) {
    const it = generateItem(rng, { slot: 'oneHand', rarity: rar })
    statSum += baseStatTotal(it)
    enchSum += it.enchantments.length
  }
  rarBudget[rar] = statSum / N
  line(`| ${RARITY[rar].label} | ${f1(statSum / N)} | ${f1(enchSum / N)} | ${RARITY[rar].enchants} |`)
}
line('')
for (let i = 1; i < RARITY_ORDER.length; i++) {
  const lo = rarBudget[RARITY_ORDER[i - 1]]
  const hi = rarBudget[RARITY_ORDER[i]]
  if (hi <= lo) failures.push(`Rarity budget not monotonic: ${RARITY_ORDER[i]} (${f1(hi)}) ≤ ${RARITY_ORDER[i - 1]} (${f1(lo)}).`)
}

// -------------------------------------------------------------- Sweep 4
// Enchantment strength on a fixed damage build.
line('## 4. Enchantment strength (single-affix uplift)')
line('')
line('Each enchantment (max roll) equipped alone on a Weaponmaster vs. no gear.')
line('**Uplift** = % change in solo DPS.')
line('')
const baseBuild = buildSpec('weaponmaster', { seed: 2 })
const baseDps = soloDpsOf(baseBuild)
const enchIds = ['might', 'precision', 'insight', 'reach', 'patience', 'cruelty', 'ruin', 'bursting', 'heavy', 'swift', 'flaming', 'frost', 'shocking', 'piercing', 'vampiric', 'executioner']
const enchRows: { id: string; uplift: number }[] = []
for (const id of enchIds) {
  const ench = rollNamedEnchant(id)
  if (!ench) continue
  const item: Item = { id: `t_${id}`, name: id, slot: 'oneHand', rarity: 'epic', base: {}, enchantments: [ench] }
  const withEnch: Sentinel = { ...baseBuild, equipment: { ...baseBuild.equipment, mainHand: item } }
  const dps = soloDpsOf(withEnch)
  enchRows.push({ id, uplift: baseDps ? (dps - baseDps) / baseDps : 0 })
}
enchRows.sort((a, b) => b.uplift - a.uplift)
line('| Enchantment | DPS uplift |')
line('|---|--:|')
for (const r of enchRows) line(`| ${r.id} | ${r.uplift >= 0 ? '+' : ''}${pct(r.uplift)} |`)
line('')

// -------------------------------------------------------------- Sweep 5
// Difficulty ceiling: standard team vs rising Threat at a fixed depth.
line('## 5. Threat ceiling (standard team, depth 8)')
line('')
line('A balanced 3-build team (Vanguard / Sharpshooter / Pyromancer, Epic gear) faces')
line('depth-8 waves at rising Threat. The **break point** is where the base falls.')
line('')
const stdTeam = [
  { sentinel: buildSpec('vanguard', { gearRarity: 'epic', seed: 8 }), slotId: 's0' },
  { sentinel: buildSpec('sharpshooter', { gearRarity: 'epic', seed: 8 }), slotId: 's3' },
  { sentinel: buildSpec('pyromancer', { gearRarity: 'epic', seed: 8 }), slotId: 's5' },
]
line('| Threat | Cleared | Base HP left | Kills |')
line('|--:|:-:|--:|--:|')
let breakPoint = 0
for (let threat = 1.0; threat <= 5.01; threat += 0.5) {
  const m = runBattle({ team: stdTeam, depth: 8, enemyHpMult: threat, baseHp: 20, maxSeconds: 90, seed: 21 })
  line(`| ×${f2(threat)} | ${m.cleared ? '✓' : '✗'} | ${f1(m.baseHpLeft)} | ${m.killCount} |`)
  if (m.cleared) breakPoint = threat
}
line('')
line(`Standard team holds depth-8 up to **Threat ×${f2(breakPoint)}**.`)
line('')
const baselineClear = runBattle({ team: stdTeam, depth: 6, enemyHpMult: 1, baseHp: 20, maxSeconds: 90, seed: 21 })
if (!baselineClear.cleared) failures.push('Standard team cannot clear depth 6 at Threat ×1 — game may be unwinnable.')

// -------------------------------------------------------------- Sweep 6
// Monte Carlo full runs: random teams + gear vs the compounding Threat ramp.
line('## 6. Monte Carlo full runs (compounding Threat vs. progression)')
line('')
line('Random teams (3–5 specs) play depths 1→10. Team **power scales with depth**')
line('(level ≈ 2+2·depth, gear rarity improving) to mirror real progression, while')
line('Threat compounds ×1.05/node and base HP (20) persists. **Win** = the boss falls.')
line('')
const RUNS = 150
const NODES = 10
let wins = 0
const depths: number[] = []
const mcRng = new RNG(2024)
const depthLevel = (d: number) => Math.min(20, 2 + d * 2)
const depthRarity = (d: number): ItemRarity =>
  d < 3 ? 'common' : d < 6 ? 'rare' : d < 9 ? 'epic' : 'legendary'
const slots = ['s3', 's0', 's5', 's1', 's4', 's2']
for (let r = 0; r < RUNS; r++) {
  const teamSize = 3 + Math.floor(mcRng.next() * 3) // 3..5
  const specIds = Array.from({ length: teamSize }, () => mcRng.pick(TIER2_NODES).id)
  let baseHp = 20
  let threat = 1
  let reached = 0
  for (let depth = 1; depth <= NODES; depth++) {
    // Rebuild the team at depth-appropriate power (compounding player strength).
    const team = specIds.map((id, i) => ({
      sentinel: buildSpec(id, { level: depthLevel(depth), gearRarity: depthRarity(depth), seed: r * 10 + i }),
      slotId: slots[i],
    }))
    const kind = depth === NODES ? 'boss' : depth % 4 === 0 ? 'elite' : 'normal'
    const m = runBattle({ team, depth, kind, enemyHpMult: threat, baseHp, maxSeconds: 70, seed: r * 100 + depth })
    baseHp = m.baseHpLeft
    if (!m.cleared || baseHp <= 0) break
    reached = depth
    threat *= kind === 'elite' ? 1.16 : 1.08 // mirrors THREAT_PER_NODE
  }
  depths.push(reached)
  if (reached >= NODES) wins++
}
const winRate = wins / RUNS
const avgDepth = mean(depths)
line(`- Runs: **${RUNS}**`)
line(`- Win rate (reached boss): **${pct(winRate)}**`)
line(`- Average depth reached: **${f1(avgDepth)} / ${NODES}**`)
line(`- Depth distribution: ${histogram(depths, NODES)}`)
line('')
if (winRate < 0.1) failures.push(`Monte Carlo win rate ${pct(winRate)} < 10% — runs may be too hard.`)
if (winRate > 0.8) failures.push(`Monte Carlo win rate ${pct(winRate)} > 80% — runs may be too easy.`)

// -------------------------------------------------------------- Summary
line('## Verdict')
line('')
if (failures.length === 0) {
  line('✅ **All balance invariants passed.**')
} else {
  line('❌ **Balance issues detected:**')
  line('')
  for (const fmsg of failures) line(`- ${fmsg}`)
}
line('')

const out = md.join('\n')
writeFileSync(new URL('./REPORT.md', import.meta.url), out)

// Console summary
console.log('=== Fieldwatch Balance ===')
console.log(`Specializations: ${TIER2_NODES.length} | offense DPS median ${f1(offMed)}, spread ${f2(Math.max(...offDps) / Math.min(...offDps))}×`)
console.log(`Threat ceiling (std team, depth 8): ×${f2(breakPoint)}`)
console.log(`Monte Carlo: ${pct(winRate)} win rate, avg depth ${f1(avgDepth)}/${NODES} over ${RUNS} runs`)
console.log(`Report written to balance/REPORT.md`)
if (failures.length) {
  console.log(`\n❌ ${failures.length} invariant(s) failed:`)
  for (const fmsg of failures) console.log('  - ' + fmsg)
  process.exit(1)
} else {
  console.log('\n✅ All balance invariants passed.')
}

// ---- helpers ----
function baseStatTotal(it: Item): number {
  const b = it.base
  // Normalise disparate base fields onto a rough "budget points" scale so the
  // rarity ladder stays comparable across weapon / off-hand / body items.
  return (
    (b.physDamage ?? 0) +
    (b.magDamage ?? 0) +
    (b.attackSpeed ?? 0) * 100 +
    (b.critChance ?? 0) * 100 +
    (b.rangeMult ?? 0) * 100 +
    (b.splashAdd ?? 0)
  )
}

function soloDpsOf(s: Sentinel): number {
  const m = runBattle({ team: [{ sentinel: s, slotId: 's3' }], depth: 6, enemyHpMult: 1.8, baseHp: 999, maxSeconds: 90, seed: 4242 })
  return m.timeSec > 0 ? m.totalDamage / m.timeSec : 0
}

/** Roll a single named enchantment at epic budget by generating items until it appears. */
function rollNamedEnchant(id: string): Enchantment | null {
  const rng = new RNG(500)
  for (let i = 0; i < 4000; i++) {
    const it = generateItem(rng, { slot: rng.pick(['oneHand', 'offHand', 'body']), rarity: 'legendary' })
    const e = it.enchantments.find((x) => x.id === id)
    if (e) return e
  }
  return null
}

function histogram(depths: number[], max: number): string {
  const counts = new Array(max + 1).fill(0)
  for (const d of depths) counts[Math.min(max, d)]++
  return counts.map((c, d) => `${d}:${c}`).join('  ')
}
