import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, posix, relative, resolve, sep } from 'node:path'
import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'

/**
 * Hand-rolled PWA service worker (M24).
 *
 * No dependency: `vite-plugin-pwa` pulls in Workbox and a build-time toolchain
 * for a ~1.5MB single-page game that needs one cache and one fetch handler.
 * This walks the finished `dist/` — which is the only moment the hashed asset
 * names and the copied `public/` files are BOTH known — and writes a worker
 * with that exact file list baked in as its precache.
 */
function pwa(): Plugin {
  /**
   * Cache-name namespace, the build-time half of it.
   *
   * This alone does NOT identify a deploy — one origin can host several
   * Fieldwatches — so the worker appends a tag derived from its own
   * registration scope at runtime. See the namespace note in the worker.
   */
  const PREFIX = 'fieldwatch-'
  /** Never precached: the worker itself, and files that aren't part of the app. */
  const SKIP = new Set(['sw.js'])
  /**
   * Attribution and licence text ship in `dist/` because they ship in
   * `public/`, but nothing in the running game ever fetches them. Precaching
   * them only spends an install request and a slice of the origin's storage
   * quota on every player, so they are excluded by extension rather than by
   * name — the next `CREDITS.md` should not need this list edited again.
   */
  const NON_RUNTIME = /\.(md|txt|map)$/i
  const skip = (f: string): boolean => SKIP.has(f) || NON_RUNTIME.test(f)

  /**
   * Art that ships in `dist/` and that no shipping code ever asks for (P3).
   *
   * The harvest that brought in the Tiny Swords kit added 86 files nothing
   * references — **115.7 KB, measured**, on top of a 1,007 KB asset tree. Every
   * one of them was an extra request during the service worker's install,
   * because `optional` was "everything that is not a bundle chunk" and the
   * walker cannot tell a wired sprite from a harvested one.
   *
   * So the precache is derived from what the BUILD actually names. A file under
   * `assets/` is precached when:
   *
   *  - its basename occurs literally in the emitted JS/CSS/HTML — which covers
   *    every nine-slice `border-image`, the icon atlas, the web-manifest icons
   *    and the fonts; or
   *  - it lives under a `DYNAMIC` prefix, where paths are built from a variable
   *    at runtime (`assets/sprites/tinyswords/${archetype}.png`,
   *    `assets/audio/ui/${name}.wav`) so no basename of theirs is ever a
   *    literal anywhere. The directory string IS a literal, and directory is
   *    the finest granularity that exists for those.
   *
   * `NEVER` then carves two directories back out of `DYNAMIC`, both measured
   * dead:
   *
   *  - **`assets/deco/`** (18 files, 18.4 KB). Harvested; `grep -r deco src/`
   *    finds the word only inside the word "decode" in the audio loader.
   *  - **`assets/sprites/tinyswords@half/`** (46 files, 83.5 KB). Generated by
   *    `scripts/prep-sprites.ts` and deliberately not consumed — `pixmap.ts`
   *    documents why at length (the champion bucket needs native density, so
   *    consuming the half pack means shipping BOTH at 322.4 KB against 236.9,
   *    and its baked halo is the pack's cool `#161C2E` where the renderer wants
   *    a warm rim light). It stays on disk because the swap is one loader line
   *    and the folder is the artifact that makes it one line; it stays out of
   *    the precache because a file nothing requests should not cost an install
   *    request.
   *
   * The rule cannot silently starve a wired asset: anything on `NEVER` whose
   * basename turns up in the build is a hard build failure below.
   */
  const DYNAMIC = ['assets/sprites/', 'assets/audio/']
  const NEVER = [/^assets\/deco\//, /^assets\/sprites\/tinyswords@half\//]

  const walk = (dir: string, root: string, out: string[] = []): string[] => {
    for (const name of readdirSync(dir)) {
      const full = join(dir, name)
      if (statSync(full).isDirectory()) walk(full, root, out)
      else out.push(relative(root, full).split(sep).join(posix.sep))
    }
    return out
  }

  let outDir = 'dist'
  /**
   * Everything ROLLUP emitted, as opposed to everything that ends up in
   * `dist/`. The difference matters: `public/` is copied in wholesale, and it
   * lands under `assets/` too (assets/sprites, assets/audio), so the output
   * path cannot tell a bundle chunk apart from a copied sprite. This set can,
   * and it is what decides which files the install refuses to go live without.
   */
  const bundleFiles = new Set<string>()
  return {
    name: 'fieldwatch-pwa',
    apply: 'build',
    configResolved(cfg) {
      outDir = cfg.build.outDir
    },
    generateBundle(_options, bundle) {
      for (const name of Object.keys(bundle)) bundleFiles.add(name)
    },
    closeBundle() {
      const root = resolve(process.cwd(), outDir)
      let files: string[]
      try {
        files = walk(root, root).filter((f) => !skip(f))
      } catch {
        return // no build output (e.g. a dry run) — nothing to precache
      }

      files.sort()

      /*
       * Two precache lists, because "some of the build" is worse than either
       * all of it or none of it.
       *
       * CRITICAL is what a cold offline launch cannot boot without: the shell
       * plus every chunk and stylesheet rollup emitted (lazy chunks included —
       * offline is exactly when they cannot be fetched on demand). If any of
       * these is missing the install is refused outright, which leaves the
       * PREVIOUS worker active with its complete cache instead of replacing a
       * working offline game with a blank page. See the install handler.
       *
       * Everything else — sprites, the ten UI wavs, the icons, the web
       * manifest, the two woff2 faces — is OPTIONAL and still added one file
       * at a time. A sprite that 404s costs that sprite; it is not worth
       * withholding a release from every player over.
       */
      const isBundleCode = (f: string): boolean => bundleFiles.has(f) && /\.(js|css)$/i.test(f)
      // Fallback for the (unreachable in a normal build) case where the rollup
      // hook never ran: assume the flat top level of assets/ is bundle output.
      const anyCode = files.some(isBundleCode)
      const critical = files.filter(
        (f) =>
          f === 'index.html' ||
          (anyCode ? isBundleCode(f) : /^assets\/[^/]+\.(js|css)$/i.test(f)),
      )
      const criticalSet = new Set(critical)

      /*
       * The reachability pass (P3). See `DYNAMIC` / `NEVER` above.
       *
       * The haystack is the emitted code, not the source: a path that survives
       * only in a JSDoc comment is not a reference, and comments are gone by
       * this point. That is what makes `assets/sprites/tinyswords@half/`
       * measurable as dead rather than arguable — `pixmap.ts` names it in prose
       * and never in an expression.
       */
      const haystack = files
        .filter((f) => /\.(js|css|html|webmanifest|json)$/i.test(f))
        .map((f) => readFileSync(join(root, f), 'utf8'))
        .join('\n')

      const base = (f: string): string => f.split('/').pop() ?? f
      /**
       * The name WITHOUT its extension, because half the references in this
       * codebase are template halves. `fx.ts` holds `['explosions', 'fire']`
       * and appends `.png` at the call site, so a basename-only test drops both
       * effect sheets — a false negative that costs an offline player the
       * explosion animation, which is far worse than the one precache entry a
       * false positive costs. Four characters minimum, so a two-letter stem
       * cannot match half a minified identifier.
       */
      const stem = (f: string): string => base(f).replace(/\.[^.]+$/, '')
      const reachable = (f: string): boolean => {
        if (!f.startsWith('assets/')) return true
        if (NEVER.some((re) => re.test(f))) return false
        if (haystack.includes(base(f))) return true
        const s = stem(f)
        if (s.length >= 4 && haystack.includes(s)) return true
        return DYNAMIC.some((d) => f.startsWith(d) && haystack.includes(d))
      }

      /*
       * A guard, not a comment. If something on `NEVER` is wired up later, the
       * build stops here instead of shipping a game whose offline install is
       * quietly missing the art it now needs.
       *
       * The test is the DIRECTORY, not the basename. Both `NEVER` entries are
       * whole folders and both are shadowed by a live folder holding the same
       * filenames — `tinyswords@half/barrel1.png` against
       * `tinyswords/barrel1.png`, which is the entire point of a half-density
       * pack. A basename test reported all 46 of them as "referenced" when
       * every one of those references was to the other copy. What actually
       * decides it is whether any emitted code ever names the folder.
       */
      const dirOf = (f: string): string => f.split('/').slice(0, -1).join('/') + '/'
      const contradicted = [...new Set(files.filter((f) => NEVER.some((re) => re.test(f))).map(dirOf))].filter(
        (d) => haystack.includes(d),
      )
      if (contradicted.length) {
        throw new Error(
          `fieldwatch-pwa: the build now names ${contradicted.join(', ')}, which is on the ` +
            `never-precache list. Take it off NEVER in vite.config.ts, or the offline install ships without it.`,
        )
      }

      const unreachable = files.filter((f) => !criticalSet.has(f) && !reachable(f))
      const optional = files.filter((f) => !criticalSet.has(f) && reachable(f))
      const url = (f: string): string => './' + f

      /*
       * The cache name has to change whenever any BYTE does, or an installed
       * player keeps the old build forever.
       *
       * Hashing the file-NAME list does not do that. JS and CSS survive it by
       * accident because Vite content-hashes their filenames, but everything
       * copied from `public/` — every sprite, all ten wavs, the icons and the
       * web manifest — keeps a fixed name. Change one of those and the old
       * digest came out identical, `sw.js` was byte-for-byte the same file, the
       * browser's byte-comparison update check found nothing to install, and
       * the worker never reinstalled: the new release was invisible to everyone
       * who already had the game. So hash the contents.
       *
       * Sizes are not a substitute — two different 4 KB sprites collide.
       *
       * Over the PRECACHED set only, since P3. Hashing files the worker never
       * stores means editing an unwired deco PNG evicts every installed
       * player's cache and re-downloads a build whose stored bytes are
       * identical — an invalidation with no content behind it.
       */
      const precached = [...critical, ...optional]
      const digest = createHash('sha256')
      let bytes = 0
      for (const f of precached) {
        const body = readFileSync(join(root, f))
        bytes += body.length
        digest.update(f).update('\0').update(body).update('\0')
      }
      const version = digest.digest('hex').slice(0, 12)
      const droppedBytes = unreachable.reduce((n, f) => n + statSync(join(root, f)).size, 0)

      /*
       * A fingerprint of THIS build's shell, used by the worker to tell the
       * app's own document apart from anything else the origin might answer a
       * navigation with: Vite always emits a content-hashed entry script, so
       * the URL is unique to this build. Its exact character length rides
       * along, because presence of the URL alone only rules out a page that
       * REPLACES the app (see the worker's own notes on the shell).
       */
      const html = readFileSync(join(root, 'index.html'), 'utf8')
      const shellMark = /<script[^>]+src="([^"]*assets\/[^"]+\.js)"/.exec(html)?.[1]
      /*
       * No fallback, on purpose.
       *
       * This used to fall back to `'id="root"'`, which every build shipped and
       * which is not a fingerprint of anything: a stale CDN edge's index.html,
       * the previous release's index.html, any document with a root div all
       * contain it. So on the day the pattern above stopped matching, the
       * install-time stale-edge check and the shell write-side check would
       * both have gone on passing — silently, everywhere, with nothing in the
       * build output to say the worker's only build-identity signal had been
       * swapped for a constant. A build that cannot produce the mark has to be
       * fixed, not shipped.
       */
      if (!shellMark) {
        throw new Error(
          'fieldwatch-pwa: no content-hashed entry script found in dist/index.html, so ' +
            "there is no fingerprint for this build's shell. The service worker's " +
            'stale-edge and shell-write checks are built on it. Fix the entry-script ' +
            'pattern in vite.config.ts (or the html transform that dropped the tag) ' +
            'before shipping — there is deliberately no fallback.',
        )
      }

      const sw = `/* Fieldwatch service worker — generated by vite.config.ts (M24). Do not edit. */
/* --------------------------------------------------------- the cache namespace
 * Cache storage is per-ORIGIN. A deploy is per-SCOPE. That gap is a bug unless
 * the name closes it: one origin routinely hosts more than one Fieldwatch —
 * \`/fieldwatch/\` beside \`/fieldwatch-public-demo/\`, prod beside staging, a PR
 * preview beside the live build — and every one of them generates the same
 * '${PREFIX}<build>' names. The activate sweep below then deleted a SIBLING
 * deploy's live cache on every release. The victim never recovers on its own:
 * its worker is already activated, so it never re-installs, and its next cold
 * offline launch falls through cachedShell() → null → Response.error(), which
 * is a blank page — the exact failure the install handler goes to such lengths
 * to prevent.
 *
 * So every name carries a tag derived from THIS registration's scope. FNV-1a
 * is ample (this is a namespace, not a checksum) and its fixed width is the
 * actual requirement: an 8-char tag can never be a prefix or a suffix of
 * another scope's tag, which raw scope paths very much can be ('/' sits inside
 * '/beta/'). The build id stays a literal so \`sw.js\` remains greppable. */
const scopeTag = (s) => {
  let h = 0x811c9dc5
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 0x01000193)
  }
  return (h >>> 0).toString(16).padStart(8, '0')
}
/* \`registration.scope\` is the truth (a host may widen it with
 * Service-Worker-Allowed); the worker's own directory is the same thing in
 * every normal deploy and is always readable. */
const SCOPE_SUFFIX = '@' + scopeTag(
  (self.registration && self.registration.scope) || new URL('./', self.location.href).href,
)
const CACHE_PREFIX = '${PREFIX}'
/* Every cache name this scope's Fieldwatch owns: prefix + build id + tag. */
const CACHE = '${PREFIX}${version}' + SCOPE_SUFFIX
/* Shape of the tag, used to tell "another scope's cache" from "a cache written
 * before tags existed". */
const TAGGED = /@[0-9a-f]{8}$/
const SHELL = './index.html'
/* This build's entry-script URL and its index.html length. See "the offline
 * shell" below for what each one can and cannot tell us. */
const SHELL_MARK = ${JSON.stringify(shellMark)}
const SHELL_LEN = ${html.length}
/* Refuse to go live without these. */
const CRITICAL = ${JSON.stringify(critical.map(url), null, 2)}
/* Nice to have offline; a miss costs that file and nothing else. */
const OPTIONAL = ${JSON.stringify(optional.map(url), null, 2)}

// ignoreVary is REQUIRED here, not a nicety: static hosts commonly answer
// assets with \`Vary: Origin\`, and Vite's entry tags carry \`crossorigin\`, so the
// page's requests send an Origin header while the precache entries (added from
// a plain URL) did not. A Vary-aware match misses every one of them and the app
// dies offline with the shell loaded but no script.
const MATCH = { ignoreVary: true }

/* ------------------------------------------------------------------- install
 * Pull the build down so the game is playable with no network — but a HALF
 * pulled build must never replace a whole one.
 *
 * This used to add every entry with \`.catch(() => {})\`, so the install
 * RESOLVED even when every asset had failed; \`skipWaiting()\` fired, activate
 * swept the previous build's complete cache, and a player who had a working
 * offline game was left with a shell whose scripts were never cached — a blank
 * page, cold, offline, with no way back. Content-hashing \`sw.js\` (right in
 * itself) widened that window from "releases that touch JS/CSS" to "every
 * release". So the critical set is all-or-nothing: one failure rejects the
 * install, this worker never activates, and the previous worker carries on
 * serving its intact cache until the network can actually deliver a build.
 */
const install = async () => {
  const c = await caches.open(CACHE)
  await Promise.all(CRITICAL.map((u) => c.add(u)))

  // One more way to precache a useless build: a CDN edge still serving the
  // PREVIOUS release's index.html while sw.js is already the new one. Every
  // request above succeeds, and the shell points at chunks this cache will
  // never hold. Catch it here, where the cost is "no update yet", instead of
  // on the player's next flight-mode launch, where the cost is the game.
  //
  // Deliberately the MARK test and not the stricter isThisBuildsShell() the
  // navigate path uses. A host that injects its own snippet into index.html
  // would fail an exact-length test on every install forever, re-downloading
  // the whole critical set each time and never granting offline play at all —
  // a worse outcome than an offline shell carrying somebody's analytics tag.
  const shell = await c.match(SHELL, MATCH)
  const text = shell ? await shell.text() : ''
  if (!text.includes(SHELL_MARK)) throw new Error('precached shell is not this build')

  // The critical set, and only the critical set, decides whether this build
  // goes live. See warm() for why the other ${optional.length} are not allowed a vote.
  await self.skipWaiting()
  return c
}

/* Pull the OPTIONAL set down afterwards, a few requests at a time.
 *
 * Deliberately not awaited by the install. It used to be — one uncapped
 * \`Promise.all\` over all ${optional.length} of them, sitting in front of \`skipWaiting()\` — which
 * put every last sprite ahead of the update: on a slow link the finished,
 * verified new build waited on files it is defined as not needing, and a worker
 * killed anywhere in that long window threw away the whole install and started
 * again from nothing. Detaching it inverts that. A kill now costs only the
 * files the warm had not reached yet, and it does not cost those for long
 * either: the runtime handler below caches what it fetches, so an unwarmed
 * sprite is simply cached on first use instead of up front.
 *
 * The concurrency cap is the other half — ${optional.length} simultaneous requests is not a
 * precache, it is a stampede, and on a metered or congested link it competes
 * with the game that is already running. */
let warming = null
const warm = (c) => {
  if (warming) return warming
  let i = 0
  const next = async () => {
    while (i < OPTIONAL.length) await c.add(OPTIONAL[i++]).catch(() => {})
  }
  warming = Promise.all(Array.from({ length: Math.min(6, OPTIONAL.length) }, next))
  return warming
}

self.addEventListener('install', (e) => {
  e.waitUntil(
    install().then(
      (c) => {
        warm(c) // detached on purpose — see warm()
      },
      (err) =>
        // Nothing can reach this half-filled cache — its name is unique to this
        // build and this scope, and this worker never activated — so drop it and
        // let the next update check start clean. If the delete is itself cut
        // short, the cache is still not stranded: a LATER build's activate
        // sweeps it (same scope tag, different build id), and a retry of THIS
        // build reopens it by name and tops up whatever is missing before the
        // shell check runs again.
        caches
          .delete(CACHE)
          .catch(() => {})
          .then(() => {
            throw err
          }),
    ),
  )
})

/* ------------------------------------------------------------------ activate
 * Drop the caches THIS SCOPE owns, except this build's.
 *
 * Not "this app's name" — that is what the namespace note at the top of this
 * file is about, and matching on the bare prefix is how a sibling deploy's
 * live cache used to get deleted on every release. A blanket sweep of
 * caches.keys() would be worse still: one origin can host a docs site, a
 * marketing page and three other apps, and none of their storage is this
 * worker's business.
 *
 * Names without a tag predate this scheme, so they carry no scope to compare —
 * but their CONTENTS do. SHELL is relative, so it resolves against this
 * worker's own scope, and only the deploy that owns that path ever put it in a
 * cache. A legacy cache holding it is this deploy's previous cache and is
 * collected; one holding some other deploy's shell is left exactly alone,
 * which is the whole point. */
const ownsShell = (k) =>
  caches
    .open(k)
    .then((c) => c.match(SHELL, MATCH))
    .then((hit) => !!hit)
    .catch(() => false)

const sweep = async () => {
  const keys = await caches.keys()
  await Promise.all(
    keys.map(async (k) => {
      if (k === CACHE || !k.startsWith(CACHE_PREFIX)) return
      if (!k.endsWith(SCOPE_SUFFIX)) {
        if (TAGGED.test(k)) return // another scope's, explicitly
        if (!(await ownsShell(k))) return // legacy, and not ours
      }
      await caches.delete(k).catch(() => {})
    }),
  )
}

self.addEventListener('activate', (e) => {
  // Collecting old caches is housekeeping; claiming the clients is the job. A
  // sweep that cannot read caches.keys() must not cost this build its clients.
  e.waitUntil(sweep().catch(() => {}).then(() => self.clients.claim()))
})

self.addEventListener('message', (e) => {
  if (e.data === 'skip-waiting') self.skipWaiting()
})

/* ----------------------------------------------------------- the offline shell
 * The cached \`./index.html\` is what a cold offline launch boots, so writing to
 * it is the single most dangerous thing this worker does. It used to store
 * EVERY navigation response unconditionally, which meant one captive-portal
 * page, one 502 from the CDN, one SSO redirect — served once, while online —
 * permanently became the app. Offline the game then booted "Sign in to use this
 * Wi-Fi" forever, and only clearing site data got it back.
 *
 * Status is not enough on its own: a captive portal answers 200 on the app's
 * own origin. So a navigation response has to be a plain, un-redirected,
 * same-origin 200 AND be this build's document before it goes near the shell.
 */
const looksLikeApp = (res) =>
  !!res && res.ok && res.status === 200 && !res.redirected && res.type === 'basic'

/* Write side — strict: only this build's own index.html may take the slot.
 *
 * Containing the entry-script URL is necessary but NOT sufficient, and the
 * comment that used to sit here ("no captive portal will ever contain that
 * exact URL") was only true of portals that REPLACE the page. One that WRAPS
 * it — "SIGN IN TO USE THIS WI-FI" prepended to the real document, which is
 * how transparent proxies actually behave — carries the URL along with
 * everything else and sailed straight through. Requiring the doctype at the
 * front and the exact byte length this build emitted costs nothing and closes
 * that shape.
 *
 * None of this is a security boundary, and it should not be sold as one:
 * anything able to rewrite the response can also pad it to length. What
 * actually stops a MITM is \`res.type === 'basic'\` plus TLS — over HTTPS no
 * intermediary can touch this response at all, and the wrap needs plain HTTP
 * or an installed root cert to exist in the first place. These checks are for
 * the mundane failures that happen on real networks without any attacker:
 * hotel portals, maintenance pages, SSO interstitials, and a CDN edge still
 * handing out the previous build's HTML.
 */
const isThisBuildsShell = (t) =>
  t.length === SHELL_LEN && /^\\s*<!doctype html/i.test(t) && t.includes(SHELL_MARK)

/* Read side — deliberately looser than the write side.
 *
 * A cached shell that is not THIS build's is still, usually, the app: a stale
 * edge, or a shell an earlier worker cached. Deleting it (what this used to do
 * on any SHELL_MARK miss) and answering Response.error() stranded the client
 * for good — the second offline reload had no shell left at all and rendered
 * an empty document. So serve anything that is structurally this app, and keep
 * deletion for a document that genuinely is not (the portal page an older,
 * less careful worker admitted), where booting it is worse than failing.
 */
const isAppDocument = (t) =>
  /<div[^>]*id="root"/.test(t) && /<script[^>]+src="[^"]*assets\\/[^"]+\\.js"/.test(t)

const cachedShell = () =>
  caches
    .open(CACHE)
    .then((c) =>
      c.match(SHELL, MATCH).then((r) => {
        if (!r) return null
        return r
          .clone()
          .text()
          .then((t) => (isAppDocument(t) ? r : c.delete(SHELL, MATCH).then(() => null)))
          // Unreadable is not the same as hostile: neither serve nor destroy.
          .catch(() => null)
      }),
    )
    .catch(() => null)

self.addEventListener('fetch', (e) => {
  const req = e.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  if (url.origin !== self.location.origin) return

  // Navigations fall back to the cached shell, which is what makes a cold
  // offline launch work at all.
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then((res) => {
          if (looksLikeApp(res)) {
            const copy = res.clone()
            // Cloned first, checked second: the check consumes a clone, and the
            // response still has to reach the page intact either way.
            res
              .clone()
              .text()
              .then((t) => {
                if (isThisBuildsShell(t)) caches.open(CACHE).then((c) => c.put(SHELL, copy)).catch(() => {})
              })
              .catch(() => {})
          }
          return res
        })
        .catch(() => cachedShell().then((r) => r || Response.error())),
    )
    return
  }

  // Everything else: cache-first, out of THIS build's cache only.
  //
  // Assets are content-hashed, so a hit is always the right bytes — but the
  // files copied from public/ are not, and a bare caches.match() searches every
  // cache on the origin. That let a non-hashed sprite or wav be served out of
  // an orphaned, half-filled cache: a crashed install's leftovers, or another
  // Fieldwatch deploy's. Naming the cache costs nothing and asks the question
  // that was meant all along.
  e.respondWith(
    caches
      .match(req, { ...MATCH, cacheName: CACHE })
      // A cacheName that does not exist yet REJECTS rather than missing.
      .catch(() => undefined)
      .then(
        (hit) =>
          hit ||
          fetch(req).then((res) => {
            if (res.ok && res.type === 'basic') {
              const copy = res.clone()
              caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {})
            }
            return res
          }),
      ),
  )
})
`
      writeFileSync(join(root, 'sw.js'), sw)
      const kb = Math.round(bytes / 1024)
      console.log(
        `fieldwatch-pwa: sw.js precaches ${precached.length} files (${kb} KB), ` +
          `${critical.length} critical, cache ${PREFIX}${version}@<scope> ` +
          `(the scope tag is computed by the worker at runtime)`,
      )
      if (unreachable.length) {
        console.log(
          `fieldwatch-pwa: ${unreachable.length} unreferenced file(s) left OUT of the precache ` +
            `(${Math.round(droppedBytes / 1024)} KB, ${unreachable.length} install requests saved). ` +
            `They still ship and are still fetchable; they are just not part of the offline set.`,
        )
      }
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), pwa()],
  base: './',
  server: {
    host: true,
    port: 5173,
  },
})
