/**
 * GENERATED by scripts/brand.ts — do not edit. Re-run `npm run brand`.
 *
 * The menu diorama and where its light sources sit, in scene pixels (one scene
 * pixel is one CSS pixel), so `MenuKeyArt` can lay CSS-only ambience exactly
 * over the lamp, the torches and the stars.
 */
import src from './keyart.png'

export const KEYART = { src, ...{"w":488,"h":272,"lamp":[228,84,5,9],"torches":[[392,102],[314,136]],"stars":[[417,8],[449,15],[174,41],[10,38],[76,27],[125,43],[99,33]],"sparks":[[412,124],[420,121],[430,116],[440,112],[450,109],[458,107]]} } as const
