#!/usr/bin/env python3
"""
Outline the Merchant Mercenaries wordmark (formerly Fieldwatch) from the shipped Crimson Text Bold face.

    pip install fonttools brotli        # one-off; not a project dependency
    python3 scripts/brand-wordmark.py   # rewrites src/assets/brand/wordmark.svg

Why outlines and not the live font: the lockup has to render identically in
places that cannot load our @font-face — sharp/librsvg when `scripts/brand.ts`
rasterises the social card and the icons, an email client, a store listing, a
press kit. Outlined glyphs are artwork made WITH the font, which the SIL OFL 1.1
permits without the artwork itself becoming Font Software; the face is the one
already recorded in public/licenses/THIRD_PARTY_NOTICES.md.

The wordmark is set, then spaced by eye — kerned in threes, not by the font's
GPOS table, which is tuned for running text at 17px rather than a logotype at
60px. Change a number below, re-run, and re-render `npm run brand` to look.
"""
import os
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
FONT = os.path.join(ROOT, 'src', 'assets', 'fonts', 'crimson-text-700.woff2')
OUT = os.path.join(ROOT, 'src', 'assets', 'brand', 'wordmark.svg')

TEXT = 'Merchant Mercenaries'
# Everything is in font units (1024 per em).
TRACK = -8  # a logotype at display size wants a touch tighter than the text setting
KERN = {
    # Fieldwatch's hand-set pairs (Fi, dw, wa, tc) do not occur in the new name.
    # Respace by eye after the first render, as before.
}


def outline(font_file, text, track, kern, out, title, note):
    font = TTFont(font_file)
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    upm = font['head'].unitsPerEm
    cap = font['OS/2'].sCapHeight
    pen = SVGPathPen(glyphs, ntos=lambda n: ('%.1f' % n).rstrip('0').rstrip('.'))
    bounds = BoundsPen(glyphs)
    x = 0
    for i, ch in enumerate(text):
        name = cmap[ord(ch)]
        # y-up font space -> y-down SVG space, baseline at y=0
        glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, x, 0)))
        glyphs[name].draw(TransformPen(bounds, (1, 0, 0, -1, x, 0)))
        x += font['hmtx'][name][0] + (track if i < len(text) - 1 else 0) + kern.get(text[i:i + 2], 0)
    x0, y0, x1, y1 = bounds.bounds
    w, h = x1 - x0, y1 - y0
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x0:.0f} {y0:.0f} {w:.0f} {h:.0f}" width="{w / upm * 48:.1f}" height="{h / upm * 48:.1f}" data-cap-height="{cap}" data-baseline="0" data-units-per-em="{upm}">
  <title>{title}</title>
  <!-- Generated by scripts/brand-wordmark.py from {note} (SIL OFL 1.1). Baseline y=0, cap height {cap}. Do not hand-edit: change the spacing there and re-run. -->
  <path fill="currentColor" d="{pen.getCommands()}"/>
</svg>
'''
    with open(out, 'w') as f:
        f.write(svg)
    print(f'outlined: {os.path.relpath(out, ROOT)} ({w:.0f}x{h:.0f} font units)')


outline(FONT, TEXT, TRACK, KERN, OUT, TEXT, 'Crimson Text Bold')
# The line under the lockup on the social card. Set, not drawn: running text.
outline(os.path.join(ROOT, 'src', 'assets', 'fonts', 'crimson-text-600.woff2'),
        'Sellswords for hire', 0, {},
        os.path.join(ROOT, 'src', 'assets', 'brand', 'tagline.svg'),
        'Sellswords for hire', 'Crimson Text SemiBold')
